# Jenkins Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
      tier: backend
  template:
    metadata:
      labels:
        app: jenkins
        tier: backend
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
            - containerPort: 50000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
    tier: backend
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
    - port: 50000
      targetPort: 50000
  type: NodePort

# Node.js Deployment and Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
      tier: frontend
  template:
    metadata:
      labels:
        app: nodejs
        tier: frontend
    spec:
      containers:
        - name: nodejs
          image: node:14
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  selector:
    app: nodejs
    tier: frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30002
  type: NodePort

# MongoDB Deployment and Service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: database
  template:
    metadata:
      labels:
        app: mongodb
        tier: database
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example # Change for a secure password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
    tier: database
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30003
  type: NodePort

